-- Generated by /ases-scaffold Step B (Sonnet).
-- DOCKER MODE: this script is mounted into postgres container at
-- /docker-entrypoint-initdb.d/01_bootstrap.sql and runs automatically as the
-- POSTGRES_USER superuser on FIRST container start.
--
-- The database and app role are already created by POSTGRES_DB / POSTGRES_USER /
-- POSTGRES_PASSWORD env vars in docker-compose.yml. This script only enables
-- extensions and grants schema permissions.
--
-- If you are running PostgreSQL OUTSIDE Docker (local install), then BEFORE
-- running this script you must first execute:
--   CREATE DATABASE jayanth_trading;
--   CREATE ROLE trading_app WITH LOGIN PASSWORD '<set_real_password>';
--   GRANT ALL PRIVILEGES ON DATABASE jayanth_trading TO trading_app;
-- Then connect to jayanth_trading and run this script:
--   psql -U postgres -d jayanth_trading -f backend/db/bootstrap.sql

CREATE EXTENSION IF NOT EXISTS pgcrypto;

GRANT ALL ON SCHEMA public TO trading_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO trading_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO trading_app;
